# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(766, 656)
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.lineEdit_verbruikDagJul = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagJul.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagJul.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagJul.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagJul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagJul.setObjectName("lineEdit_verbruikDagJul")
        self.gridLayout_29.addWidget(self.lineEdit_verbruikDagJul, 0, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_1)
        self.label_54.setObjectName("label_54")
        self.gridLayout_29.addWidget(self.label_54, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem4, 0, 4, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_1)
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.gridLayout_29.addWidget(self.label_55, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_29, 9, 5, 1, 1)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.lineEdit_verbruikDagJun = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagJun.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagJun.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagJun.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagJun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagJun.setObjectName("lineEdit_verbruikDagJun")
        self.gridLayout_28.addWidget(self.lineEdit_verbruikDagJun, 0, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_1)
        self.label_52.setObjectName("label_52")
        self.gridLayout_28.addWidget(self.label_52, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem6, 0, 4, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_1)
        self.label_53.setText("")
        self.label_53.setObjectName("label_53")
        self.gridLayout_28.addWidget(self.label_53, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_28, 8, 5, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.lineEdit_verbruikDagAug = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagAug.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagAug.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagAug.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagAug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagAug.setObjectName("lineEdit_verbruikDagAug")
        self.gridLayout_30.addWidget(self.lineEdit_verbruikDagAug, 0, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_1)
        self.label_56.setObjectName("label_56")
        self.gridLayout_30.addWidget(self.label_56, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem8, 0, 4, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_1)
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.gridLayout_30.addWidget(self.label_57, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_30, 10, 5, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem9, 0, 0, 1, 1)
        self.lineEdit_verbruikDagFeb = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagFeb.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagFeb.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagFeb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagFeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagFeb.setObjectName("lineEdit_verbruikDagFeb")
        self.gridLayout_23.addWidget(self.lineEdit_verbruikDagFeb, 0, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_1)
        self.label_42.setObjectName("label_42")
        self.gridLayout_23.addWidget(self.label_42, 0, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem10, 0, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_1)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.gridLayout_23.addWidget(self.label_43, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_23, 3, 5, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.lineEdit_verbruikDagMei = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagMei.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagMei.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagMei.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagMei.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagMei.setObjectName("lineEdit_verbruikDagMei")
        self.gridLayout_27.addWidget(self.lineEdit_verbruikDagMei, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_1)
        self.label_50.setObjectName("label_50")
        self.gridLayout_27.addWidget(self.label_50, 0, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem11, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem12, 0, 4, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_1)
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.gridLayout_27.addWidget(self.label_51, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_27, 7, 5, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.lineEdit_verbruikDagSep = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagSep.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagSep.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagSep.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagSep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagSep.setObjectName("lineEdit_verbruikDagSep")
        self.gridLayout_31.addWidget(self.lineEdit_verbruikDagSep, 0, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.tab_1)
        self.label_58.setObjectName("label_58")
        self.gridLayout_31.addWidget(self.label_58, 0, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem13, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem14, 0, 4, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_1)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.gridLayout_31.addWidget(self.label_59, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_31, 11, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 8, 0, 1, 1)
        self.lineEdit_verbruikNov = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikNov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikNov.setObjectName("lineEdit_verbruikNov")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikNov, 13, 2, 1, 1)
        self.lineEdit_verbruikJul = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikJul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikJul.setObjectName("lineEdit_verbruikJul")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikJul, 9, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 10, 0, 1, 1)
        self.lineEdit_verbruikSep = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikSep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikSep.setObjectName("lineEdit_verbruikSep")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikSep, 11, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 15, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_verbruikMei = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikMei.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikMei.setObjectName("lineEdit_verbruikMei")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikMei, 7, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 12, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 11, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_verbruikApr = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikApr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikApr.setObjectName("lineEdit_verbruikApr")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikApr, 6, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 13, 0, 1, 1)
        self.lineEdit_verbruikMaart = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikMaart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikMaart.setObjectName("lineEdit_verbruikMaart")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikMaart, 5, 2, 1, 1)
        self.lineEdit_verbruikJun = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikJun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikJun.setObjectName("lineEdit_verbruikJun")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikJun, 8, 2, 1, 1)
        self.lineEdit_verbruikJan = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikJan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikJan.setObjectName("lineEdit_verbruikJan")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikJan, 2, 2, 1, 1)
        self.lineEdit_verbruikFeb = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikFeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikFeb.setObjectName("lineEdit_verbruikFeb")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikFeb, 3, 2, 1, 1)
        self.lineEdit_verbruikDec = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikDec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDec.setObjectName("lineEdit_verbruikDec")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikDec, 15, 2, 1, 1)
        self.lineEdit_verbruikOkt = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikOkt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikOkt.setObjectName("lineEdit_verbruikOkt")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikOkt, 12, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 9, 0, 1, 1)
        self.lineEdit_verbruikAug = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikAug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikAug.setObjectName("lineEdit_verbruikAug")
        self.gridLayout_3.addWidget(self.lineEdit_verbruikAug, 10, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_1)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 8, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_1)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 5, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_1)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_1)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 10, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_1)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 9, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_1)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 1, 2, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.lineEdit_verbruikDagJan = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagJan.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagJan.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagJan.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagJan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagJan.setObjectName("lineEdit_verbruikDagJan")
        self.gridLayout_21.addWidget(self.lineEdit_verbruikDagJan, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_1)
        self.label_27.setObjectName("label_27")
        self.gridLayout_21.addWidget(self.label_27, 0, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem15, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem16, 0, 4, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_1)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout_21.addWidget(self.label_41, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_21, 2, 5, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_1)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 6, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 1, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_1)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 15, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_1)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 7, 3, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 1, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_1)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 13, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_1)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 11, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_1)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_1)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 12, 3, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem19, 0, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem20, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_1)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_22.addWidget(self.label_26, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_22, 1, 5, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.lineEdit_verbruikDagApr = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagApr.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagApr.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagApr.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagApr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagApr.setObjectName("lineEdit_verbruikDagApr")
        self.gridLayout_26.addWidget(self.lineEdit_verbruikDagApr, 0, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_1)
        self.label_48.setObjectName("label_48")
        self.gridLayout_26.addWidget(self.label_48, 0, 3, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem21, 0, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem22, 0, 4, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_1)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.gridLayout_26.addWidget(self.label_49, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_26, 6, 5, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.lineEdit_verbruikDagOkt = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagOkt.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagOkt.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagOkt.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagOkt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagOkt.setObjectName("lineEdit_verbruikDagOkt")
        self.gridLayout_32.addWidget(self.lineEdit_verbruikDagOkt, 0, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.tab_1)
        self.label_60.setObjectName("label_60")
        self.gridLayout_32.addWidget(self.label_60, 0, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem23, 0, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem24, 0, 4, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_1)
        self.label_61.setText("")
        self.label_61.setObjectName("label_61")
        self.gridLayout_32.addWidget(self.label_61, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_32, 12, 5, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.lineEdit_verbruikDagMaart = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagMaart.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagMaart.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagMaart.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagMaart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagMaart.setObjectName("lineEdit_verbruikDagMaart")
        self.gridLayout_25.addWidget(self.lineEdit_verbruikDagMaart, 0, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_1)
        self.label_46.setObjectName("label_46")
        self.gridLayout_25.addWidget(self.label_46, 0, 3, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem25, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem26, 0, 4, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_1)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.gridLayout_25.addWidget(self.label_47, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_25, 5, 5, 1, 1)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.lineEdit_verbruikDagDec = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagDec.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagDec.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagDec.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagDec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagDec.setObjectName("lineEdit_verbruikDagDec")
        self.gridLayout_38.addWidget(self.lineEdit_verbruikDagDec, 0, 2, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.tab_1)
        self.label_72.setObjectName("label_72")
        self.gridLayout_38.addWidget(self.label_72, 0, 3, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem27, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem28, 0, 4, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.tab_1)
        self.label_73.setText("")
        self.label_73.setObjectName("label_73")
        self.gridLayout_38.addWidget(self.label_73, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_38, 15, 5, 1, 1)
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.lineEdit_verbruikDagNov = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_verbruikDagNov.sizePolicy().hasHeightForWidth())
        self.lineEdit_verbruikDagNov.setSizePolicy(sizePolicy)
        self.lineEdit_verbruikDagNov.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_verbruikDagNov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_verbruikDagNov.setObjectName("lineEdit_verbruikDagNov")
        self.gridLayout_36.addWidget(self.lineEdit_verbruikDagNov, 0, 2, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.tab_1)
        self.label_68.setObjectName("label_68")
        self.gridLayout_36.addWidget(self.label_68, 0, 3, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem29, 0, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem30, 0, 4, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.tab_1)
        self.label_69.setText("")
        self.label_69.setObjectName("label_69")
        self.gridLayout_36.addWidget(self.label_69, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_36, 13, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 6, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 6, 0, 1, 1)
        self.lineEdit_ePrijsHeen = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_ePrijsHeen.setObjectName("lineEdit_ePrijsHeen")
        self.gridLayout_4.addWidget(self.lineEdit_ePrijsHeen, 6, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_1)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 8, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem31, 12, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_1)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 8, 0, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.tab_1)
        self.label_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName("label_75")
        self.gridLayout_4.addWidget(self.label_75, 9, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem32, 0, 2, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.tab_1)
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName("label_74")
        self.gridLayout_4.addWidget(self.label_74, 9, 1, 1, 1)
        self.lineEdit_ePrijsTerugTax = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_ePrijsTerugTax.setObjectName("lineEdit_ePrijsTerugTax")
        self.gridLayout_4.addWidget(self.lineEdit_ePrijsTerugTax, 9, 2, 1, 1)
        self.lineEdit_ePrijsTerug = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_ePrijsTerug.setObjectName("lineEdit_ePrijsTerug")
        self.gridLayout_4.addWidget(self.lineEdit_ePrijsTerug, 8, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 3, 2, 1, 1)
        self.label_ = QtWidgets.QLabel(self.tab_1)
        self.label_.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_.setObjectName("label_")
        self.gridLayout_4.addWidget(self.label_, 1, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.tab_1)
        self.label_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_4.addWidget(self.label_80, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_1)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 0, 1, 1)
        self.lineEdit_netbeheerkosten = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_netbeheerkosten.setObjectName("lineEdit_netbeheerkosten")
        self.gridLayout_4.addWidget(self.lineEdit_netbeheerkosten, 2, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_1)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem33, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_1)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 6, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem34, 6, 3, 1, 1)
        self.lineEdit_vasteLeveringskosten = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_vasteLeveringskosten.setObjectName("lineEdit_vasteLeveringskosten")
        self.gridLayout_4.addWidget(self.lineEdit_vasteLeveringskosten, 1, 2, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.tab_1)
        self.label_79.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_79.setObjectName("label_79")
        self.gridLayout_4.addWidget(self.label_79, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 6, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem35, 8, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem36, 12, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 3, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem37, 9, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_verdeel = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_verdeel.setObjectName("pushButton_verdeel")
        self.gridLayout_10.addWidget(self.pushButton_verdeel, 0, 4, 1, 1)
        self.lineEdit_verbruikTotaal = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_verbruikTotaal.setObjectName("lineEdit_verbruikTotaal")
        self.gridLayout_10.addWidget(self.lineEdit_verbruikTotaal, 0, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem38, 1, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem39, 0, 3, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.tab_1)
        self.label_77.setObjectName("label_77")
        self.gridLayout_10.addWidget(self.label_77, 0, 2, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.tab_1)
        self.label_76.setObjectName("label_76")
        self.gridLayout_10.addWidget(self.label_76, 0, 0, 1, 1)
        self.checkBox_gelijkeMaanden = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_gelijkeMaanden.setObjectName("checkBox_gelijkeMaanden")
        self.gridLayout_10.addWidget(self.checkBox_gelijkeMaanden, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 3, 0, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem40, 2, 1, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem41, 8, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        TabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem42, 0, 2, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem43, 11, 1, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem44, 2, 1, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem45, 9, 1, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem46, 10, 3, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem47, 0, 2, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.tab_2)
        self.label_78.setObjectName("label_78")
        self.gridLayout_12.addWidget(self.label_78, 0, 0, 1, 1)
        self.lineEdit_panelenTot = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_panelenTot.setObjectName("lineEdit_panelenTot")
        self.gridLayout_12.addWidget(self.lineEdit_panelenTot, 0, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.tab_2)
        self.label_82.setObjectName("label_82")
        self.gridLayout_12.addWidget(self.label_82, 1, 0, 1, 1)
        self.comboBox_orientatie = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_orientatie.setObjectName("comboBox_orientatie")
        self.comboBox_orientatie.addItem("")
        self.comboBox_orientatie.addItem("")
        self.comboBox_orientatie.addItem("")
        self.comboBox_orientatie.addItem("")
        self.comboBox_orientatie.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_orientatie, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 3, 1, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_opbrengstOkt = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstOkt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstOkt.setObjectName("lineEdit_opbrengstOkt")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstOkt, 12, 2, 1, 1)
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.label_93 = QtWidgets.QLabel(self.tab_2)
        self.label_93.setText("")
        self.label_93.setObjectName("label_93")
        self.gridLayout_43.addWidget(self.label_93, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_43, 7, 5, 1, 1)
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.label_85 = QtWidgets.QLabel(self.tab_2)
        self.label_85.setText("")
        self.label_85.setObjectName("label_85")
        self.gridLayout_39.addWidget(self.label_85, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_39, 9, 5, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.tab_2)
        self.label_98.setObjectName("label_98")
        self.gridLayout_15.addWidget(self.label_98, 15, 0, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.tab_2)
        self.label_100.setObjectName("label_100")
        self.gridLayout_15.addWidget(self.label_100, 5, 0, 1, 1)
        self.lineEdit_opbrengstMei = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstMei.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstMei.setObjectName("lineEdit_opbrengstMei")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstMei, 7, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.tab_2)
        self.label_102.setObjectName("label_102")
        self.gridLayout_15.addWidget(self.label_102, 11, 0, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.tab_2)
        self.label_101.setObjectName("label_101")
        self.gridLayout_15.addWidget(self.label_101, 12, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.tab_2)
        self.label_103.setObjectName("label_103")
        self.gridLayout_15.addWidget(self.label_103, 2, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.tab_2)
        self.label_104.setObjectName("label_104")
        self.gridLayout_15.addWidget(self.label_104, 3, 0, 1, 1)
        self.lineEdit_opbrengstApr = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstApr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstApr.setObjectName("lineEdit_opbrengstApr")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstApr, 6, 2, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.tab_2)
        self.label_105.setObjectName("label_105")
        self.gridLayout_15.addWidget(self.label_105, 13, 0, 1, 1)
        self.lineEdit_opbrengstMaart = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstMaart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstMaart.setObjectName("lineEdit_opbrengstMaart")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstMaart, 5, 2, 1, 1)
        self.lineEdit_opbrengstJun = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstJun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstJun.setObjectName("lineEdit_opbrengstJun")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstJun, 8, 2, 1, 1)
        self.lineEdit_opbrengstFeb = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstFeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstFeb.setObjectName("lineEdit_opbrengstFeb")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstFeb, 3, 2, 1, 1)
        self.lineEdit_opbrengstDec = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstDec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstDec.setObjectName("lineEdit_opbrengstDec")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstDec, 15, 2, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.tab_2)
        self.label_109.setObjectName("label_109")
        self.gridLayout_15.addWidget(self.label_109, 2, 3, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.tab_2)
        self.label_106.setObjectName("label_106")
        self.gridLayout_15.addWidget(self.label_106, 9, 0, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.tab_2)
        self.label_108.setObjectName("label_108")
        self.gridLayout_15.addWidget(self.label_108, 5, 3, 1, 1)
        self.lineEdit_opbrengstAug = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstAug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstAug.setObjectName("lineEdit_opbrengstAug")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstAug, 10, 2, 1, 1)
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.label_87 = QtWidgets.QLabel(self.tab_2)
        self.label_87.setText("")
        self.label_87.setObjectName("label_87")
        self.gridLayout_40.addWidget(self.label_87, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_40, 8, 5, 1, 1)
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.label_95 = QtWidgets.QLabel(self.tab_2)
        self.label_95.setText("")
        self.label_95.setObjectName("label_95")
        self.gridLayout_44.addWidget(self.label_95, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_44, 11, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 8, 0, 1, 1)
        self.lineEdit_opbrengstNov = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstNov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstNov.setObjectName("lineEdit_opbrengstNov")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstNov, 13, 2, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.tab_2)
        self.label_96.setObjectName("label_96")
        self.gridLayout_15.addWidget(self.label_96, 7, 0, 1, 1)
        self.lineEdit_opbrengstJul = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstJul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstJul.setObjectName("lineEdit_opbrengstJul")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstJul, 9, 2, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.tab_2)
        self.label_97.setObjectName("label_97")
        self.gridLayout_15.addWidget(self.label_97, 10, 0, 1, 1)
        self.lineEdit_opbrengstSep = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstSep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstSep.setObjectName("lineEdit_opbrengstSep")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstSep, 11, 2, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.tab_2)
        self.label_99.setObjectName("label_99")
        self.gridLayout_15.addWidget(self.label_99, 6, 0, 1, 1)
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.label_89 = QtWidgets.QLabel(self.tab_2)
        self.label_89.setText("")
        self.label_89.setObjectName("label_89")
        self.gridLayout_41.addWidget(self.label_89, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_41, 10, 5, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.tab_2)
        self.label_107.setObjectName("label_107")
        self.gridLayout_15.addWidget(self.label_107, 8, 3, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.tab_2)
        self.label_110.setObjectName("label_110")
        self.gridLayout_15.addWidget(self.label_110, 10, 3, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.tab_2)
        self.label_111.setObjectName("label_111")
        self.gridLayout_15.addWidget(self.label_111, 9, 3, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.tab_2)
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.gridLayout_15.addWidget(self.label_112, 1, 2, 1, 1)
        self.gridLayout_45 = QtWidgets.QGridLayout()
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.label_114 = QtWidgets.QLabel(self.tab_2)
        self.label_114.setText("")
        self.label_114.setObjectName("label_114")
        self.gridLayout_45.addWidget(self.label_114, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_45, 2, 5, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.tab_2)
        self.label_115.setObjectName("label_115")
        self.gridLayout_15.addWidget(self.label_115, 6, 3, 1, 1)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem48, 1, 4, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.tab_2)
        self.label_116.setObjectName("label_116")
        self.gridLayout_15.addWidget(self.label_116, 15, 3, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.tab_2)
        self.label_118.setObjectName("label_118")
        self.gridLayout_15.addWidget(self.label_118, 13, 3, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem49, 1, 3, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.tab_2)
        self.label_117.setObjectName("label_117")
        self.gridLayout_15.addWidget(self.label_117, 7, 3, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.tab_2)
        self.label_119.setObjectName("label_119")
        self.gridLayout_15.addWidget(self.label_119, 11, 3, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.tab_2)
        self.label_120.setObjectName("label_120")
        self.gridLayout_15.addWidget(self.label_120, 3, 3, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.tab_2)
        self.label_121.setObjectName("label_121")
        self.gridLayout_15.addWidget(self.label_121, 12, 3, 1, 1)
        self.gridLayout_46 = QtWidgets.QGridLayout()
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.gridLayout_15.addLayout(self.gridLayout_46, 1, 5, 1, 1)
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.label_91 = QtWidgets.QLabel(self.tab_2)
        self.label_91.setText("")
        self.label_91.setObjectName("label_91")
        self.gridLayout_42.addWidget(self.label_91, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_42, 3, 5, 1, 1)
        self.gridLayout_47 = QtWidgets.QGridLayout()
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.label_124 = QtWidgets.QLabel(self.tab_2)
        self.label_124.setText("")
        self.label_124.setObjectName("label_124")
        self.gridLayout_47.addWidget(self.label_124, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_47, 6, 5, 1, 1)
        self.gridLayout_48 = QtWidgets.QGridLayout()
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.label_126 = QtWidgets.QLabel(self.tab_2)
        self.label_126.setText("")
        self.label_126.setObjectName("label_126")
        self.gridLayout_48.addWidget(self.label_126, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_48, 12, 5, 1, 1)
        self.gridLayout_49 = QtWidgets.QGridLayout()
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.label_128 = QtWidgets.QLabel(self.tab_2)
        self.label_128.setText("")
        self.label_128.setObjectName("label_128")
        self.gridLayout_49.addWidget(self.label_128, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_49, 5, 5, 1, 1)
        self.gridLayout_50 = QtWidgets.QGridLayout()
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.label_130 = QtWidgets.QLabel(self.tab_2)
        self.label_130.setText("")
        self.label_130.setObjectName("label_130")
        self.gridLayout_50.addWidget(self.label_130, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_50, 15, 5, 1, 1)
        self.gridLayout_51 = QtWidgets.QGridLayout()
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.label_132 = QtWidgets.QLabel(self.tab_2)
        self.label_132.setText("")
        self.label_132.setObjectName("label_132")
        self.gridLayout_51.addWidget(self.label_132, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_51, 13, 5, 1, 1)
        self.lineEdit_opbrengstJan = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_opbrengstJan.setFrame(True)
        self.lineEdit_opbrengstJan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_opbrengstJan.setDragEnabled(False)
        self.lineEdit_opbrengstJan.setReadOnly(False)
        self.lineEdit_opbrengstJan.setClearButtonEnabled(False)
        self.lineEdit_opbrengstJan.setObjectName("lineEdit_opbrengstJan")
        self.gridLayout_15.addWidget(self.lineEdit_opbrengstJan, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_15, 8, 1, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem50, 5, 2, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem51, 4, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 3, 5, 1, 1)
        self.lineEdit_omvormerRendement = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_omvormerRendement.setObjectName("lineEdit_omvormerRendement")
        self.gridLayout_11.addWidget(self.lineEdit_omvormerRendement, 3, 3, 1, 1)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem52, 4, 2, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem53, 10, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 3, 4, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem54 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem54, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_5, 8, 3, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_11.addWidget(self.radioButton, 6, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setObjectName("label_63")
        self.gridLayout_11.addWidget(self.label_63, 5, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.tab_2)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_11.addWidget(self.toolButton, 6, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_133.setFont(font)
        self.label_133.setObjectName("label_133")
        self.gridLayout_16.addWidget(self.label_133, 0, 0, 1, 1)
        TabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_einddatum = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_einddatum.setObjectName("lineEdit_einddatum")
        self.gridLayout_13.addWidget(self.lineEdit_einddatum, 3, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.tab_3)
        self.label_92.setObjectName("label_92")
        self.gridLayout_13.addWidget(self.label_92, 7, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setObjectName("label_44")
        self.gridLayout_13.addWidget(self.label_44, 0, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_3)
        self.label_64.setObjectName("label_64")
        self.gridLayout_13.addWidget(self.label_64, 3, 0, 1, 1)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem55, 4, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_13.addWidget(self.label_65, 5, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        self.label_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_13.addWidget(self.label_45, 0, 5, 1, 1)
        self.comboBox_verbruikVSproductie_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_verbruikVSproductie_2.setObjectName("comboBox_verbruikVSproductie_2")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.comboBox_verbruikVSproductie_2.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_verbruikVSproductie_2, 9, 1, 1, 1)
        self.checkBox_verbruikVSproductie_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_verbruikVSproductie_2.setObjectName("checkBox_verbruikVSproductie_2")
        self.gridLayout_13.addWidget(self.checkBox_verbruikVSproductie_2, 9, 0, 1, 1)
        self.lineEdit_batterijCap = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_batterijCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_batterijCap.setObjectName("lineEdit_batterijCap")
        self.gridLayout_13.addWidget(self.lineEdit_batterijCap, 0, 6, 1, 1)
        spacerItem56 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem56, 4, 2, 1, 1)
        self.checkBox_verbruikVSproductie_3 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_verbruikVSproductie_3.setObjectName("checkBox_verbruikVSproductie_3")
        self.gridLayout_13.addWidget(self.checkBox_verbruikVSproductie_3, 10, 0, 1, 1)
        self.checkBox_verbruikVSproductie_1 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_verbruikVSproductie_1.setObjectName("checkBox_verbruikVSproductie_1")
        self.gridLayout_13.addWidget(self.checkBox_verbruikVSproductie_1, 8, 0, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.tab_3)
        self.label_113.setObjectName("label_113")
        self.gridLayout_13.addWidget(self.label_113, 7, 9, 1, 1)
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem57, 11, 0, 1, 1)
        self.comboBox_aankoopVSteruglevering_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_aankoopVSteruglevering_2.setObjectName("comboBox_aankoopVSteruglevering_2")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.comboBox_aankoopVSteruglevering_2.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_aankoopVSteruglevering_2, 9, 6, 1, 1)
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem58, 0, 2, 1, 1)
        self.checkBox_batterij_lvl_mean = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_batterij_lvl_mean.setObjectName("checkBox_batterij_lvl_mean")
        self.gridLayout_13.addWidget(self.checkBox_batterij_lvl_mean, 8, 9, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.tab_3)
        self.label_94.setObjectName("label_94")
        self.gridLayout_13.addWidget(self.label_94, 7, 5, 1, 1)
        self.checkBox_batterij_lvl_exact = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_batterij_lvl_exact.setObjectName("checkBox_batterij_lvl_exact")
        self.gridLayout_13.addWidget(self.checkBox_batterij_lvl_exact, 9, 9, 1, 1)
        self.lineEdit_startdatum = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_startdatum.setObjectName("lineEdit_startdatum")
        self.gridLayout_13.addWidget(self.lineEdit_startdatum, 0, 1, 1, 1)
        self.checkBox_aankoopVSteruglevering_1 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_aankoopVSteruglevering_1.setObjectName("checkBox_aankoopVSteruglevering_1")
        self.gridLayout_13.addWidget(self.checkBox_aankoopVSteruglevering_1, 8, 5, 1, 1)
        spacerItem59 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem59, 4, 7, 1, 1)
        self.checkBox_aankoopVSteruglevering_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_aankoopVSteruglevering_2.setObjectName("checkBox_aankoopVSteruglevering_2")
        self.gridLayout_13.addWidget(self.checkBox_aankoopVSteruglevering_2, 9, 5, 1, 1)
        self.checkBox_aankoopVSteruglevering_3 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_aankoopVSteruglevering_3.setObjectName("checkBox_aankoopVSteruglevering_3")
        self.gridLayout_13.addWidget(self.checkBox_aankoopVSteruglevering_3, 10, 5, 1, 1)
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem60, 6, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.tab_3)
        self.label_62.setObjectName("label_62")
        self.gridLayout_13.addWidget(self.label_62, 0, 7, 1, 1)
        spacerItem61 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem61, 4, 3, 1, 1)
        spacerItem62 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem62, 4, 6, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab_3)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_13.addWidget(self.label_66, 3, 5, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.tab_3)
        self.label_67.setObjectName("label_67")
        self.gridLayout_13.addWidget(self.label_67, 3, 6, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        spacerItem63 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem63, 11, 0, 1, 1)
        spacerItem64 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem64, 8, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_8.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem65 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem65, 0, 4, 1, 1)
        spacerItem66 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem66, 0, 5, 1, 1)
        self.label_result1b = QtWidgets.QLabel(self.tab_3)
        self.label_result1b.setText("")
        self.label_result1b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_result1b.setObjectName("label_result1b")
        self.gridLayout_19.addWidget(self.label_result1b, 3, 2, 1, 1)
        self.label_result3 = QtWidgets.QLabel(self.tab_3)
        self.label_result3.setText("")
        self.label_result3.setObjectName("label_result3")
        self.gridLayout_19.addWidget(self.label_result3, 5, 0, 1, 1)
        self.label_result2 = QtWidgets.QLabel(self.tab_3)
        self.label_result2.setText("")
        self.label_result2.setObjectName("label_result2")
        self.gridLayout_19.addWidget(self.label_result2, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_19.addWidget(self.label_20, 2, 0, 1, 1)
        spacerItem67 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem67, 1, 0, 1, 1)
        self.label_result3b = QtWidgets.QLabel(self.tab_3)
        self.label_result3b.setText("")
        self.label_result3b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_result3b.setObjectName("label_result3b")
        self.gridLayout_19.addWidget(self.label_result3b, 5, 2, 1, 1)
        self.pushButton_bereken = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_bereken.setProperty("bereken", False)
        self.pushButton_bereken.setObjectName("pushButton_bereken")
        self.gridLayout_19.addWidget(self.pushButton_bereken, 0, 0, 1, 1)
        spacerItem68 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem68, 6, 0, 1, 1)
        self.label_result2b = QtWidgets.QLabel(self.tab_3)
        self.label_result2b.setText("")
        self.label_result2b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_result2b.setObjectName("label_result2b")
        self.gridLayout_19.addWidget(self.label_result2b, 4, 2, 1, 1)
        spacerItem69 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem69, 0, 2, 1, 1)
        self.label_result1 = QtWidgets.QLabel(self.tab_3)
        self.label_result1.setText("")
        self.label_result1.setObjectName("label_result1")
        self.gridLayout_19.addWidget(self.label_result1, 3, 0, 1, 1)
        spacerItem70 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem70, 1, 1, 1, 1)
        self.label_result3c = QtWidgets.QLabel(self.tab_3)
        self.label_result3c.setText("")
        self.label_result3c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_result3c.setObjectName("label_result3c")
        self.gridLayout_19.addWidget(self.label_result3c, 5, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_19, 9, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        TabWidget.addTab(self.tab_3, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.lineEdit_verbruikDagJul.setText(_translate("TabWidget", "50"))
        self.label_54.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagJun.setText(_translate("TabWidget", "50"))
        self.label_52.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagAug.setText(_translate("TabWidget", "50"))
        self.label_56.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagFeb.setText(_translate("TabWidget", "50"))
        self.label_42.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagMei.setText(_translate("TabWidget", "50"))
        self.label_50.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagSep.setText(_translate("TabWidget", "50"))
        self.label_58.setText(_translate("TabWidget", "%"))
        self.label_8.setText(_translate("TabWidget", "juni"))
        self.lineEdit_verbruikNov.setText(_translate("TabWidget", "357.5"))
        self.lineEdit_verbruikJul.setText(_translate("TabWidget", "357.5"))
        self.label_7.setText(_translate("TabWidget", "mei"))
        self.label_10.setText(_translate("TabWidget", "augustus"))
        self.lineEdit_verbruikSep.setText(_translate("TabWidget", "357.5"))
        self.label_14.setText(_translate("TabWidget", "december"))
        self.label_6.setText(_translate("TabWidget", "april"))
        self.label_5.setText(_translate("TabWidget", "maart"))
        self.lineEdit_verbruikMei.setText(_translate("TabWidget", "357.5"))
        self.label_12.setText(_translate("TabWidget", "oktober"))
        self.label_11.setText(_translate("TabWidget", "september"))
        self.label_3.setText(_translate("TabWidget", "januari"))
        self.label_4.setText(_translate("TabWidget", "februari"))
        self.lineEdit_verbruikApr.setText(_translate("TabWidget", "357.5"))
        self.label_13.setText(_translate("TabWidget", "november"))
        self.lineEdit_verbruikMaart.setText(_translate("TabWidget", "357.5"))
        self.lineEdit_verbruikJun.setText(_translate("TabWidget", "357.5"))
        self.lineEdit_verbruikJan.setText(_translate("TabWidget", "357.5"))
        self.lineEdit_verbruikFeb.setText(_translate("TabWidget", "357.5"))
        self.lineEdit_verbruikDec.setText(_translate("TabWidget", "357.5"))
        self.lineEdit_verbruikOkt.setText(_translate("TabWidget", "357.5"))
        self.label_9.setText(_translate("TabWidget", "juli"))
        self.lineEdit_verbruikAug.setText(_translate("TabWidget", "357.5"))
        self.label_33.setText(_translate("TabWidget", "Kwh"))
        self.label_30.setText(_translate("TabWidget", "Kwh"))
        self.label_28.setText(_translate("TabWidget", "Kwh"))
        self.label_36.setText(_translate("TabWidget", "Kwh"))
        self.label_35.setText(_translate("TabWidget", "Kwh"))
        self.label_34.setText(_translate("TabWidget", "verbruik"))
        self.lineEdit_verbruikDagJan.setText(_translate("TabWidget", "50"))
        self.label_27.setText(_translate("TabWidget", "%"))
        self.label_31.setText(_translate("TabWidget", "Kwh"))
        self.label_40.setText(_translate("TabWidget", "Kwh"))
        self.label_32.setText(_translate("TabWidget", "Kwh"))
        self.label_39.setText(_translate("TabWidget", "Kwh"))
        self.label_37.setText(_translate("TabWidget", "Kwh"))
        self.label_29.setText(_translate("TabWidget", "Kwh"))
        self.label_38.setText(_translate("TabWidget", "Kwh"))
        self.label_26.setText(_translate("TabWidget", "gedeelte overdag"))
        self.lineEdit_verbruikDagApr.setText(_translate("TabWidget", "50"))
        self.label_48.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagOkt.setText(_translate("TabWidget", "50"))
        self.label_60.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagMaart.setText(_translate("TabWidget", "50"))
        self.label_46.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagDec.setText(_translate("TabWidget", "50"))
        self.label_72.setText(_translate("TabWidget", "%"))
        self.lineEdit_verbruikDagNov.setText(_translate("TabWidget", "50"))
        self.label_68.setText(_translate("TabWidget", "%"))
        self.label_2.setText(_translate("TabWidget", "prijs per Kwh"))
        self.lineEdit_ePrijsHeen.setText(_translate("TabWidget", "0.22"))
        self.label_25.setText(_translate("TabWidget", "€"))
        self.label_24.setText(_translate("TabWidget", "teruglever prijs per Kwh"))
        self.label_75.setText(_translate("TabWidget", "Teruglever belasting"))
        self.label_74.setText(_translate("TabWidget", "%"))
        self.lineEdit_ePrijsTerugTax.setText(_translate("TabWidget", "0.00"))
        self.lineEdit_ePrijsTerug.setText(_translate("TabWidget", "0.07"))
        self.lineEdit_3.setText(_translate("TabWidget", "0.85"))
        self.label_.setText(_translate("TabWidget", "vaste leveringskosten (per dag)"))
        self.label_80.setText(_translate("TabWidget", "€"))
        self.label_18.setText(_translate("TabWidget", "netbeheerkosten (per dag)"))
        self.lineEdit_netbeheerkosten.setText(_translate("TabWidget", "0.20"))
        self.label_17.setText(_translate("TabWidget", "toeslagen (per dag)"))
        self.label_16.setText(_translate("TabWidget", "€"))
        self.label_15.setText(_translate("TabWidget", "€"))
        self.lineEdit_vasteLeveringskosten.setText(_translate("TabWidget", "0.20"))
        self.label_79.setText(_translate("TabWidget", "€"))
        self.pushButton_verdeel.setText(_translate("TabWidget", "verdeel"))
        self.lineEdit_verbruikTotaal.setText(_translate("TabWidget", "4290"))
        self.label_77.setText(_translate("TabWidget", "Kwh"))
        self.label_76.setText(_translate("TabWidget", "Totaal verbruik"))
        self.checkBox_gelijkeMaanden.setText(_translate("TabWidget", "gelijke maanden"))
        self.label.setText(_translate("TabWidget", "Uw energieverbruik"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_1), _translate("TabWidget", "1) Energieverbruik"))
        self.label_78.setText(_translate("TabWidget", "Totaal aantal panelen"))
        self.lineEdit_panelenTot.setText(_translate("TabWidget", "24"))
        self.label_82.setText(_translate("TabWidget", "Orientatie richting"))
        self.comboBox_orientatie.setItemText(0, _translate("TabWidget", "Zuid"))
        self.comboBox_orientatie.setItemText(1, _translate("TabWidget", "Noord"))
        self.comboBox_orientatie.setItemText(2, _translate("TabWidget", "Oost"))
        self.comboBox_orientatie.setItemText(3, _translate("TabWidget", "West"))
        self.comboBox_orientatie.setItemText(4, _translate("TabWidget", "Vlak"))
        self.lineEdit_opbrengstOkt.setText(_translate("TabWidget", "18.38"))
        self.label_98.setText(_translate("TabWidget", "december"))
        self.label_100.setText(_translate("TabWidget", "maart"))
        self.lineEdit_opbrengstMei.setText(_translate("TabWidget", "44.00"))
        self.label_102.setText(_translate("TabWidget", "september"))
        self.label_101.setText(_translate("TabWidget", "oktober"))
        self.label_103.setText(_translate("TabWidget", "januari"))
        self.label_104.setText(_translate("TabWidget", "februari"))
        self.lineEdit_opbrengstApr.setText(_translate("TabWidget", "37.29"))
        self.label_105.setText(_translate("TabWidget", "november"))
        self.lineEdit_opbrengstMaart.setText(_translate("TabWidget", "26.17"))
        self.lineEdit_opbrengstJun.setText(_translate("TabWidget", "40.33"))
        self.lineEdit_opbrengstFeb.setText(_translate("TabWidget", "18.04"))
        self.lineEdit_opbrengstDec.setText(_translate("TabWidget", "5.13"))
        self.label_109.setText(_translate("TabWidget", "Kwh"))
        self.label_106.setText(_translate("TabWidget", "juli"))
        self.label_108.setText(_translate("TabWidget", "Kwh"))
        self.lineEdit_opbrengstAug.setText(_translate("TabWidget", "35.08"))
        self.label_23.setText(_translate("TabWidget", "juni"))
        self.lineEdit_opbrengstNov.setText(_translate("TabWidget", "9.38"))
        self.label_96.setText(_translate("TabWidget", "mei"))
        self.lineEdit_opbrengstJul.setText(_translate("TabWidget", "40.58"))
        self.label_97.setText(_translate("TabWidget", "augustus"))
        self.lineEdit_opbrengstSep.setText(_translate("TabWidget", "26.38"))
        self.label_99.setText(_translate("TabWidget", "april"))
        self.label_107.setText(_translate("TabWidget", "Kwh"))
        self.label_110.setText(_translate("TabWidget", "Kwh"))
        self.label_111.setText(_translate("TabWidget", "Kwh"))
        self.label_112.setText(_translate("TabWidget", "obrengst per paneel"))
        self.label_115.setText(_translate("TabWidget", "Kwh"))
        self.label_116.setText(_translate("TabWidget", "Kwh"))
        self.label_118.setText(_translate("TabWidget", "Kwh"))
        self.label_117.setText(_translate("TabWidget", "Kwh"))
        self.label_119.setText(_translate("TabWidget", "Kwh"))
        self.label_120.setText(_translate("TabWidget", "Kwh"))
        self.label_121.setText(_translate("TabWidget", "Kwh"))
        self.lineEdit_opbrengstJan.setText(_translate("TabWidget", "6.38"))
        self.label_21.setText(_translate("TabWidget", "rendement omvormer"))
        self.lineEdit_omvormerRendement.setText(_translate("TabWidget", "95"))
        self.label_22.setText(_translate("TabWidget", "%"))
        self.radioButton.setText(_translate("TabWidget", "Gebruik .csv bestanden"))
        self.label_63.setText(_translate("TabWidget", "Opbrengst:"))
        self.toolButton.setText(_translate("TabWidget", "..."))
        self.label_133.setText(_translate("TabWidget", "Zonnepanelen opbrengst"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "2) Zonnepanelen"))
        self.label_19.setText(_translate("TabWidget", "Bereken"))
        self.lineEdit_einddatum.setText(_translate("TabWidget", "31-12-2019"))
        self.label_92.setText(_translate("TabWidget", "verbruik vs productie"))
        self.label_44.setText(_translate("TabWidget", "startdatum"))
        self.label_64.setText(_translate("TabWidget", "einddatum"))
        self.label_65.setText(_translate("TabWidget", "Plot figuren:"))
        self.label_45.setText(_translate("TabWidget", "batterij cappaciteit:"))
        self.comboBox_verbruikVSproductie_2.setItemText(0, _translate("TabWidget", "januari"))
        self.comboBox_verbruikVSproductie_2.setItemText(1, _translate("TabWidget", "februari"))
        self.comboBox_verbruikVSproductie_2.setItemText(2, _translate("TabWidget", "maart"))
        self.comboBox_verbruikVSproductie_2.setItemText(3, _translate("TabWidget", "april"))
        self.comboBox_verbruikVSproductie_2.setItemText(4, _translate("TabWidget", "mei"))
        self.comboBox_verbruikVSproductie_2.setItemText(5, _translate("TabWidget", "juni"))
        self.comboBox_verbruikVSproductie_2.setItemText(6, _translate("TabWidget", "juli"))
        self.comboBox_verbruikVSproductie_2.setItemText(7, _translate("TabWidget", "augustus"))
        self.comboBox_verbruikVSproductie_2.setItemText(8, _translate("TabWidget", "september"))
        self.comboBox_verbruikVSproductie_2.setItemText(9, _translate("TabWidget", "oktober"))
        self.comboBox_verbruikVSproductie_2.setItemText(10, _translate("TabWidget", "november"))
        self.comboBox_verbruikVSproductie_2.setItemText(11, _translate("TabWidget", "december"))
        self.checkBox_verbruikVSproductie_2.setText(_translate("TabWidget", "voor hele maand"))
        self.lineEdit_batterijCap.setText(_translate("TabWidget", "0"))
        self.checkBox_verbruikVSproductie_3.setText(_translate("TabWidget", "per dag"))
        self.checkBox_verbruikVSproductie_1.setText(_translate("TabWidget", "1 dag per maand"))
        self.label_113.setText(_translate("TabWidget", "batterij"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(0, _translate("TabWidget", "januari"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(1, _translate("TabWidget", "februari"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(2, _translate("TabWidget", "maart"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(3, _translate("TabWidget", "april"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(4, _translate("TabWidget", "mei"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(5, _translate("TabWidget", "juni"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(6, _translate("TabWidget", "juli"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(7, _translate("TabWidget", "augustus"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(8, _translate("TabWidget", "september"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(9, _translate("TabWidget", "oktober"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(10, _translate("TabWidget", "november"))
        self.comboBox_aankoopVSteruglevering_2.setItemText(11, _translate("TabWidget", "december"))
        self.checkBox_batterij_lvl_mean.setText(_translate("TabWidget", "batterij level (gemiddeld)"))
        self.label_94.setText(_translate("TabWidget", "aankoop vs teruglevering"))
        self.checkBox_batterij_lvl_exact.setText(_translate("TabWidget", "batterij level (exact)"))
        self.lineEdit_startdatum.setText(_translate("TabWidget", "01-01-2019"))
        self.checkBox_aankoopVSteruglevering_1.setText(_translate("TabWidget", "1 dag per maand"))
        self.checkBox_aankoopVSteruglevering_2.setText(_translate("TabWidget", "voor hele maand"))
        self.checkBox_aankoopVSteruglevering_3.setText(_translate("TabWidget", "per dag"))
        self.label_62.setText(_translate("TabWidget", "kWh"))
        self.label_66.setText(_translate("TabWidget", "opties van tesla:"))
        self.label_67.setText(_translate("TabWidget", " 6.4 en 135 kWh"))
        self.label_20.setText(_translate("TabWidget", "Resultaat"))
        self.pushButton_bereken.setText(_translate("TabWidget", "bereken"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "3) Bereken"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

